# Generated by Django 5.2.8 on 2026-08-07 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The requested loan amount', max_digits=12)),
                ('purpose', models.TextField(help_text='The purpose for which the loan is requested')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-employed'), ('business_owner', 'Business Owner'), ('student', 'Student'), ('unemployed', 'Unemployed'), ('retired', 'Retired')], help_text='Current employment status of the applicant', max_length=30)),
                ('monthly_income', models.DecimalField(decimal_places=2, help_text='Monthly income of the applicant', max_digits=12)),
                ('duration_months', models.PositiveIntegerField(help_text='Loan duration in months')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the loan application', max_length=20)),
                ('admin_comment', models.TextField(blank=True, help_text='Optional comment from the admin regarding the application', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the application was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the application was last updated')),
                ('applicant', models.ForeignKey(help_text='The user who submitted the loan application', on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
